name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.0.0)"
        required: true
        type: string

jobs:
  # Create release package
  create-package:
    name: Create Release Package
    runs-on: ubuntu-latest
    container:
      image: tikiwiki/tikiwiki-ci:8.1-qa
    outputs:
      package-name: ${{ steps.package.outputs.name }}
      package-path: ${{ steps.package.outputs.path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create package
        id: package
        run: |
          # Get version from tag or input
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi

          echo "Creating package for version: $VERSION"

          # Create package archive (matches GitLab CI exactly)
          PACK_FILES_FOLDERS_LIST="lib composer.json README.md LICENSE"
          PACKAGE_NAME="imagine-${VERSION}.tar.gz"
          tar czf "$PACKAGE_NAME" ${PACK_FILES_FOLDERS_LIST}

          echo "name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "path=$PACKAGE_NAME" >> $GITHUB_OUTPUT

          echo "Package created: $PACKAGE_NAME"
          ls -lh "$PACKAGE_NAME"

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.package.outputs.name }}
          path: ${{ steps.package.outputs.path }}
          retention-days: 30

  # Create GitHub release
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: create-package
    container:
      image: tikiwiki/tikiwiki-ci:8.1-qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.create-package.outputs.package-name }}
          path: .

      - name: Extract version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            Release of ${{ steps.version.outputs.version }}

            **Package Download:**
            - [${{ needs.create-package.outputs.package-name }}](https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/${{ needs.create-package.outputs.package-name }})
          files: ${{ needs.create-package.outputs.package-name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
